name: trigger gitlab job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: rcmorano/gitlab-webhook-trigger@master
      env:
        GITLAB_WEBHOOK_URL: ${{ secrets.GITLAB_WEBHOOK_URL }}
        GITLAB_REF_TO_TRIGGER: ${{ secrets.GITLAB_REF_TO_TRIGGER }}
        SOCKS5_PROXY: ${{ secrets.SOCKS5_PROXY }}
